/// Flutter icons Partnerum
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Partnerum
///      fonts:
///       - asset: fonts/Partnerum.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Partnerum {
  Partnerum._();

  static const _kFontFam = 'Partnerum';

  static const IconData add_photo = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData add = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData address = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData arrow_down = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData back = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData checkbox_off_light = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData checkbox_on_light = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData city = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData clear = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData guest = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData help = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData image_gallery = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData info__1_ = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData info = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData metro = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData more_vert = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData offer = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData order = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData percent = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData phone = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData profile = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData radio_off_light = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData radio_on_light = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData rooms = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData ruble = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData send = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData walk = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData correct = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe81f, fontFamily: _kFontFam);
}
